package com.mycompany.queueproject2;
import java.util.Arrays;
import java.util.Queue;
import java.util.Stack;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author kondraty_946191
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    
    public static boolean isPalindrome(String[] list) {
        // create a queue and a stack using the list of strings
        Queue<String> queue = new LinkedList<>(List.of(list));
        Stack<String> stack = new Stack<>();
        queue.forEach(stack::push);

        // check if the list is a palindrome
        while (!queue.isEmpty()) {
            if (!queue.poll().equals(stack.pop())) {
                return false;
            }
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindow_Label_Title = new javax.swing.JLabel();
        MainWindow_Label_TypeHere = new javax.swing.JLabel();
        MainWindow_TextField_UserInput = new javax.swing.JTextField();
        MainWindow_Button_Check = new javax.swing.JButton();
        MainWindow_TextField_Answer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainWindow_Label_Title.setText("Queue Basics - Palindrome Check ");

        MainWindow_Label_TypeHere.setText("write your list here:");

        MainWindow_Button_Check.setText("CHECK");
        MainWindow_Button_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_Button_CheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(MainWindow_Label_TypeHere)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MainWindow_TextField_UserInput)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(MainWindow_Label_Title)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainWindow_TextField_Answer)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(MainWindow_Button_Check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainWindow_Label_Title)
                .addGap(18, 18, 18)
                .addComponent(MainWindow_Label_TypeHere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_TextField_UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(MainWindow_Button_Check)
                .addGap(18, 18, 18)
                .addComponent(MainWindow_TextField_Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainWindow_Button_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_Button_CheckActionPerformed
        String input = MainWindow_TextField_UserInput.getText();
        String[] list = input.split(" ");
        boolean palindrome = isPalindrome(list);

        if(palindrome == true){
            MainWindow_TextField_Answer.setText(Arrays.toString(list) + " is a palinlist.");
            return;
        }
        MainWindow_TextField_Answer.setText(Arrays.toString(list) + " is not a palinlist.");
    }//GEN-LAST:event_MainWindow_Button_CheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MainWindow().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainWindow_Button_Check;
    private javax.swing.JLabel MainWindow_Label_Title;
    private javax.swing.JLabel MainWindow_Label_TypeHere;
    private javax.swing.JTextField MainWindow_TextField_Answer;
    private javax.swing.JTextField MainWindow_TextField_UserInput;
    // End of variables declaration//GEN-END:variables
}
